In [2]:
import pandas as pd
import requests
import json
active_date = '2022-03-29'

In [3]:
price_history = pd.read_json('price_collection.json')
price_history.columns = ['Date', 'Ticker', 'Volume', 'Open', 'Low', 'High', 'Close']
price_history.sort_values('Date', ascending=True, inplace=True)
price_history = price_history[price_history['Date'] > '2023-03-01']
price_history = price_history.drop(columns=['Volume'])

In [4]:
iss_url = 'https://iss.moex.com/iss/engines/stock/markets/shares/boards/TQBR/securities.json?iss.meta=off&iss.only=marketdata&marketdata.columns=SECID,OPEN,LOW,HIGH,LAST'
response = requests.get(iss_url)
raw_data = json.loads(response.text)
#file_name = 'securities.json'
#with open(file_name, "r") as read_file:
#    raw_data = json.load(read_file)
#    read_file.close()

In [5]:
#SECID,OPEN,LOW,HIGH,LAST
for i in raw_data["marketdata"]["data"]:
    'Date', 'Ticker', 'Open', 'Low', 'High', 'Close'
    new_row = {'Date':active_date, 'Ticker':i[0], 'Open':i[1], 'Low':i[2], 'High':i[3], 'Close':i[4]} 
    price_history = price_history.append(new_row, ignore_index=True)

In [38]:
one_t = price_history[price_history['Ticker'] == 'TGKB']
count_ema = one_t['Close'].to_frame()
count_ema['Dayly_EMA'] = count_ema['Close'].ewm(span=20).mean()
new_row = {'Date':'2023-03-30', 'Ticker':'ABRD', 'Open':0, 'Low':0, 'High':0, 'Close':0.004658} 
one_t = one_t.append(new_row, ignore_index=True)
count_ema = one_t['Close'].to_frame()
count_ema['Dayly_EMA'] = count_ema['Close'].ewm(span=20).mean()

In [39]:
count_ema

       Close  Dayly_EMA
0   0.004590   0.004590
1   0.004580   0.004585
2   0.004660   0.004612
3   0.004660   0.004626
4   0.004640   0.004629
5   0.004590   0.004621
6   0.004560   0.004610
7   0.004585   0.004605
8   0.004560   0.004598
9   0.004550   0.004591
10  0.004515   0.004580
11  0.004620   0.004585
12  0.004515   0.004576
13  0.004705   0.004593
14  0.004770   0.004614
15  0.004775   0.004633
16  0.004715   0.004643
17  0.004725   0.004652
18  0.004700   0.004658
19  0.004658   0.004658